name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build Json Sort
        run: nix build .#json-sort -L
      - name: Build Json Sort Web
        run: nix build .#json-sort-web -L
